### ISSUE TITLE
Fix account delete

### ISSUE THREAD

**Issue by oskarrough** [radio4000/supabase#8]
When a user wants to delete their account, we do it through a Supabase function:

https://github.com/radio4000/supabase/blob/6e04e65c2fc6fbb4eb2e90c4af0c82efc2820180/radio4000.sql#L123-L131

but when you call it, it errors with this

```js
{
    "code": "23503",
    "details": "Key (id)=(35c4e5ee-4f69-44f9-a09e-8e6375c2c8e9) is still referenced from table \"channel_track\".",
    "hint": null,
    "message": "update or delete on table \"users\" violates foreign key constraint \"channel_track_user_id_fkey\" on table \"channel_track\""
}
```

The `user_channel` table references the `auth.user` with the `user_id` column. The column is set to cascade on delete, e.g. it will delete any `user_channel` records that references the deleted user.

So I don't understand why it fails.

**Comment by oskarrough** [comment]
I tried changing the function to only delete the `auth.user`, which should actually delete anything that references it as well. Assuming the cascade-stuff is properly set up.

**Comment by user-09876** [comment]
Maybe, in term of UX, we could "just have":
- delete channel + all its tracks
- delete user, if all channels have been deleted

So a user would have to go through remove all their radios to remove their account?

That way we can prevent a user "mis-deleting" one radio they forgot about?

I'm afraid of the nuclear impact caused by mis-clicking this button....

Or would could make a check, in the supabase backend, to enforce the user auth token is less than 5 minutes old (or retype their password to auth). That way we're more sure it's the actual user, and not someone "accidentally" deleting someone else's radio?

Also, we could automagically send a JSON dump of deleted radio by email, so even if you delete, you have a sort of backup :}

**Comment by oskarrough** [comment]
That's a good idea with the email backup!

Making it harder UX-wise is also a good idea, still the function should work. Thinking the SQL schema could use another look..

**Comment by oskarrough** [comment]
Looks like this fixed the functionality part of it https://github.com/radio4000/supabase/commit/bc2af99991a77423ab966b91726220fb0640f53e

Then we can continue to improve the UX of it
